name: angel3_portal
version: 0.1.0
description: Angel3 framework web portal
publish_to: none
environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  angular: ^6.0.1
  angular_router: ^2.0.0
  angular_forms: ^3.0.0
  angular_components: ^1.0.2
  skawa_material_components: ^1.5.0
  firebase: ^8.0.0
  crypto: ^2.1.5
   
dev_dependencies:
  angular_test: ^3.0.0
  build_runner: ^1.11.1
  build_test: ^1.3.6
  build_web_compilers: ^2.16.3
  test: ^1.16.5
  sass_builder: ^2.1.3
  pedantic: ^1.0.0